[project]
name = "obdb-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.0.6",
    "dbt-duckdb>=1.9.4",
    "duckdb>=1.3.2",
    "pandas>=2.3.2",
    "pytest>=9.0.2",
]
